tasks:
- init: sudo apt update -y && sudo apt upgrade -y && git clone -b eugenoptic44-file-downloader https://codeberg.org/eUgEntOptIc44/Area-Generator/ AreaGenerator && cd AreaGenerator &&  java -cp "gson-2.9.1.jar" Main.java
vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens